apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbexporter
spec:
  selector: # valida todos os pods com a label app: mongodb e precisam ser iguais nas labels e matchLabels
    matchLabels:
      app: mongodbexporter
  template:
    metadata:
      labels:
        app: mongodbexporter
    spec:
      containers:
        - name: mongodbexporter
          image: rampss/mongo_exporter:latest
          env:
            - name: MONGODB_URI
              value: "mongodb://mongouser:mongopwd@mongodb:27017"
          ports:
            - containerPort: 9216

---

apiVersion: v1
kind: Service
metadata:
  name: mongodbexporter-service
spec:
  selector:
    app: mongodbexporter
  ports:
  - port: 9216
    targetPort: 9216
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodbexporter-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: exporter.192.168.15.43.nip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mongodbexporter-service
              port:
                number: 9216

